#spring相关
spring:
   application:
    name: boot-client


#服务器相关
server:
  port: 8003

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#    healthcheck:
#      enabled: true