#spring相关
spring:
   application:
    name: boot-client


#服务器相关
server:
  port: 8100

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/
#    healthcheck:
#      enabled: true