#服务器相关

application:
    name: boot-service
server:
  port: 80

#健康检查
management:
  port: 54001
  health:
    mail:
      enabled: false
info:
  app:
      name: "@project.name@" #从pom.xml中获取
      description: "@project.description@"
      version: "@project.version@"
      spring-boot-version: "@project.parent.version@"


#注册服务
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/
    healthcheck:
      enabled: true

#spring相关
spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 8
      min-idle: 1
      max-active: 8
      max-wait: -1
    timeout: 1000
#    password:

#日志相关
logging:
  config: classpath:log4j.properties
